name: Java CI

on:
  pull_request:
    types:
      - opened
    branches:
      - dev

jobs:
  build and test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: checkout the code
      uses: actions/checkout@v3

    - name: Set up Java version
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: unit test with maven
      run: mvn test
      working-directory: ./PortalBackend/Java

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./PortalBackend/Java
