name: Java CI CD
  
on:
  push:
    branches: main
      
jobs: 
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: checkout the code
      uses: actions/checkout@v3

    - name: Set up Java version
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install

    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: ./PortalBackend/Java
        file: ./Dockerfile

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push Docker image
      uses: azure/docker-login@v1
      with:
        login-server: vishwassregistry.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push Docker image
      run: |
        docker build -t vishwassregistry.azurecr.io/java_test:v1 .
        docker push vishwassregistry.azurecr.io/java_test:v1

    - name: Deploy to AKS
      uses: azure/aks-set-context@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroup: vishwaas-rg
        clusterName: vishwaas-cluster

            #- name: Apply Kubernetes manifests
            #run: |
            #kubectl apply -f <path-to-your-manifests>
